name: augpt_env
channels:
 - defaults
dependencies:
 - bzip2=1.0.8
 - ca-certificates
 - libffi=3.4.4
 - ncurses=6.4
 - openssl=3.0.15
 - pip=25.0
 - python=3.11.9
 - readline=8.2
 - setuptools=75.8.0
 - sqlite=3.45.3
 - tk=8.6.14
 - tzdata=2025a=h04d1e81_0
 - wheel=0.45.1
 - xz=5.4.6
 - zlib=1.2.13
 - jq
 - pip:
   - annotated-types==0.7.0
   - anyio==4.8.0
   - blis==1.2.0
   - catalogue==2.0.10
   - certifi==2024.12.14
   - cffi==1.17.1
   - charset-normalizer==3.4.1
   - click==8.1.8
   - cloudpathlib==0.20.0
   - confection==0.1.5
   - cryptography==44.0.0
   - cymem==2.0.11
   - distro==1.9.0
   - globus-sdk==3.50.0
   - h11==0.14.0
   - httpcore==1.0.7
   - httpx==0.28.1
   - idna==3.10
   - jinja2==3.1.5
   - jiter==0.8.2
   - langcodes==3.5.0
   - language-data==1.3.0
   - marisa-trie==1.2.1
   - markdown-it-py==3.0.0
   - markupsafe==3.0.2
   - mdurl==0.1.2
   - murmurhash==1.0.12
   - numpy==2.2.2
   - openai==1.60.2
   - packaging==24.2
   - pdfminer==20191125
   - pdfminer-six==20240706
   - preshed==3.0.9
   - pycparser==2.22
   - pycryptodome==3.21.0
   - pydantic==2.10.6
   - pydantic-core==2.27.2
   - pygments==2.19.1
   - pyjwt==2.10.1
   - pypdf2==3.0.1
   - pyyaml==6.0.2
   - requests==2.32.3
   - rich==13.9.4
   - shellingham==1.5.4
   - smart-open==7.1.0
   - sniffio==1.3.1
   - spacy==3.8.4
   - spacy-legacy==3.0.12
   - spacy-loggers==1.0.5
   - https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0.tar.gz
   - srsly==2.5.1
   - thinc==8.3.4
   - tqdm==4.67.1
   - typer==0.15.1
   - typing-extensions==4.12.2
   - urllib3==2.3.0
   - wasabi==1.1.3
   - weasel==0.4.1
   - wrapt==1.17.2

